# Generated by Django 4.0.4 on 2022-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('movie_tags', models.CharField(default='', max_length=300)),
                ('popularity', models.CharField(default='', max_length=300)),
                ('genres', models.CharField(max_length=100)),
                ('cast', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
