# Generated by Django 4.0.4 on 2022-05-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderapp', '0002_movie_movie_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_keywords',
            new_name='movie_tags',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
