# Generated by Django 4.0.4 on 2022-05-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderapp', '0003_alter_history_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='tp',
            field=models.DateTimeField(null=True),
        ),
    ]
