# Generated by Django 4.0.4 on 2022-05-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderapp', '0003_rename_movie_keywords_movie_movie_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.CharField(default='', max_length=300),
        ),
    ]
