# Generated by Django 4.0.4 on 2022-05-22 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderapp', '0004_remove_movie_movie_duration_remove_movie_year_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
