# Generated by Django 4.0.4 on 2022-05-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommenderapp', '0006_movie_image_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
